  purge_interval: 1
  purge_keep_days: 5
  include:
    domains:
      - sensor
      - switch
      - binary_sensor
      - climate
      - lock
      - light
  exclude:
    entities:
     - sensor.since_last_boot
     - sensor.date
     - sensor.time
     - sensor.wine_cooling_since
     - sensor.pws_weather_1d
     - sensor.pws_weather_1n
     - sensor.pws_weather_2d
     - sensor.pws_weather_2n
     - sensor.pws_weather_3d
     - sensor.pws_weather_3n
     - sensor.pws_weather_4d
     - sensor.pws_weather_4n
     - sensor.entrancemd_tripped
     - sensor.familymd_tripped
     - sensor.frontdoor_tripped
     - sensor.pega
     - sensor.exel
     - sensor.home_alarm_keypad
     - sensor.current_solar_power
     - sensor.cpu_used
     - sensor.basementmd_tripped
     - binary_sensor.entrance_motion
     - binary_sensor.family_motion
