  - platform: mqtt
    name: "Fireplace Switch"
    state_topic: "ha/fireplace"
    command_topic: "myhome/fireplace"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
#  - platform: tplink
#    host: 192.168.1.38
